arb-dir: lib/l10n
template-arb-file: intl_vi.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/generated
untranslated-messages-file: lib/l10n/untranslated.json
