name: health_apps
description: "A Flutter project for health tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.9.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  fl_chart: ^0.68.0
  uuid: ^4.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  form_field_validator: ^1.1.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
