name: health_apps
description: "A Flutter project for health tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  google_fonts: ^5.0.0  
  timeago: ^3.3.0
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.0
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.9.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  fl_chart: ^0.68.0
  uuid: ^4.2.1
  firebase_messaging: ^14.7.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  form_field_validator: ^1.1.0
  font_awesome_flutter: ^10.8.0
  google_sign_in_web: ^0.12.4
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/a.png
    - assets/a2.png
    - assets/google_icon.png
    - assets/xoa.png

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
