// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAteDHCR0gPbkxIPQyql0UfAwTDZ518fKI',
    appId: '1:938119019838:web:80e776b115a85b2ba5406f',
    messagingSenderId: '938119019838',
    projectId: 'health-apps-16496',
    authDomain: 'health-apps-16496.firebaseapp.com',
    storageBucket: 'health-apps-16496.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVrggBYBRWTnJr0c52SoLuqIBfV2FhY4',
    appId: '1:938119019838:android:9ac6f253c41dd726a5406f',
    messagingSenderId: '938119019838',
    projectId: 'health-apps-16496',
    storageBucket: 'health-apps-16496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1k35EhsaPybhrFqTLyBTOHAc7auB5bw',
    appId: '1:938119019838:ios:be755bc232b4acd7a5406f',
    messagingSenderId: '938119019838',
    projectId: 'health-apps-16496',
    storageBucket: 'health-apps-16496.firebasestorage.app',
    iosClientId: '938119019838-t2002blfi5u3i531g5c7h54ldn3lacod.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1k35EhsaPybhrFqTLyBTOHAc7auB5bw',
    appId: '1:938119019838:ios:be755bc232b4acd7a5406f',
    messagingSenderId: '938119019838',
    projectId: 'health-apps-16496',
    storageBucket: 'health-apps-16496.firebasestorage.app',
    iosClientId: '938119019838-t2002blfi5u3i531g5c7h54ldn3lacod.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAteDHCR0gPbkxIPQyql0UfAwTDZ518fKI',
    appId: '1:938119019838:web:6a7ccccdc5d39c7ba5406f',
    messagingSenderId: '938119019838',
    projectId: 'health-apps-16496',
    authDomain: 'health-apps-16496.firebaseapp.com',
    storageBucket: 'health-apps-16496.firebasestorage.app',
  );
}
